#!/usr/bin/python3
#
# T-Rax roof controller for the Raspberry Pi
#
# This is a roll-off roof controller specifically designed and built for
# Robert Ferguson Observatory (https://rfo.org) but the code will hopefully
# be generic enough that it can be adapted for other roll-off roofs.
# See README.md for details.

import argparse
from datetime import datetime
from gpiozero import DigitalInputDevice, DigitalOutputDevice
import logging
import os
import signal
import sys
import threading

import device
import test_mode
import util

version = 'v0.9'        # T-Rax version
heartInterval = 1       # Seconds between heartbeats (drives SIGALRM)
statusInterval = 60     # Seconds between status updates without input changes

# Hard coded GPIO setup -- should these be in a dict?
class TraxGpio:
    def __init__(self):
        self.weatherOk = device.Sensor(pin=4, name='wx');
        self.bldgPowerIn = device.Sensor(pin=17, name='bldg');
        self.mountPowerIn = device.Sensor(pin=22, name='mntin');
        self.roofPowerIn = device.Sensor(pin=27, name='roofin');
        self.mountParked = device.Sensor(pin=25, name='park');
        self.roofOpen = device.Sensor(pin=23, name='open');
        self.roofClosed = device.Sensor(pin=24, name='close');

        self.heartLed = device.Control(pin=13, name='heart')
        self.mountPowerOut = device.Control(pin=6, name='mntout', active_high=False)
        self.roofPowerOut = device.Control(pin=5, name='roofout', active_high=False)
        self.laserPowerOut = device.Control(pin=16, name='laser')
        self.fobOutput = device.Control(pin=26, name='fob')

def beatHeart(output=0, step=0):
    if (step == 0):
        output.on()
        threading.Timer(0.1, beatHeart, [output,1]).start()
    elif (step == 1):
        output.off()
        threading.Timer(0.05, beatHeart, [output,2]).start()
    elif (step == 2):
        output.on()
        threading.Timer(0.1, beatHeart, [output,3]).start()
    elif (step == 3):
        output.off()
    else:
        logging.error("WTF? beatHeart() called with step %".format(step))

def perSecond():
    if (int(datetime.now().second) % 2 == 0):
        beatHeart(gpio.heartLed.device)
    if (int(datetime.now().second) % statusInterval == 0):
        logging.info(device.printStatus())
    threading.Timer(1.0, perSecond).start()  # Redispatch self

def main():

    default_logfile = '/var/log/trax.log'

    parser = argparse.ArgumentParser(description='T-Rax roof controller.')
    parser.add_argument('--test-mode', dest='test_mode', action='store_true', help='enter test mode')
    parser.add_argument('--log-file', '-L', dest='logfile', action='store', help='log filename (default {})'.format(default_logfile))
    args = parser.parse_args()

    loggingConfig = dict(format = "%(asctime)s [%(levelname)s] %(message)s", datefmt = "%Y-%m-%d %H:%M:%S", level = logging.INFO)
    if (sys.stdin.isatty() and not args.logfile):
        print("TTY detected; logging to stdout")
    else:
        loggingConfig['filename'] = args.logfile if args.logfile else default_logfile;
    logging.basicConfig(**loggingConfig)
    logging.info("Initializing T-Rax for the Raspberry Pi {}".format(version))

    global gpio
    gpio = TraxGpio()

    # Start the self perpetuating per second timer
    perSecond()

    logging.info(device.printStatus())

    if (args.test_mode):
        test = test_mode.TestMode()

    # Loop forever
    while True:
        signal.pause()

if __name__ == "__main__":
    main()
